# Generated by Django 4.2.17 on 2024-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
    ]
