# Generated by Django 4.2.17 on 2024-12-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billrequest',
            old_name='user',
            new_name='gainer',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='gainer',
        ),
        migrations.RenameField(
            model_name='lawyer',
            old_name='user',
            new_name='gainer',
        ),
    ]
