# Generated by Django 4.2.17 on 2024-12-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_billrequest_gainer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billrequest',
            old_name='gainer',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='gainer',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='lawyer',
            old_name='gainer',
            new_name='profile',
        ),
    ]
