# Generated by Django 4.2.17 on 2024-12-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('home', '0003_rename_gainer_billrequest_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='QaA',
        ),
    ]
