# Generated by Django 5.1.4 on 2025-01-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_legalcategory_rename_category_lawyertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='profile',
        ),
    ]
