# Generated by Django 5.1.4 on 2025-01-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_news_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='image',
        ),
    ]
