# Generated by Django 4.2.17 on 2025-01-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('home', '0011_rename_images_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadKhastCaregory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DadKhastNevisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.profile')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dadkhastcaregory')),
            ],
        ),
        migrations.DeleteModel(
            name='BillRequest',
        ),
    ]
