# Generated by Django 5.1.4 on 2025-01-03 17:41

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_images_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='lawyer_images'),
        ),
    ]
