# Generated by Django 4.2.17 on 2025-01-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_lawyer_image'),
        ('home', '0013_contactus_date_dadkhastnevisi_date_and_more'),
    ]

    operations = [
    ]
