# Generated by Django 5.1.4 on 2025-01-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20250103_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='date',
            field=models.DateField(),
        ),
    ]
