# Generated by Django 4.2.17 on 2025-01-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_lawyer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadkhastnevisi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dadkhast_request'),
        ),
        migrations.AlterField(
            model_name='dadkhastnevisi',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
